### PR TITLE
Database access code

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR brings all prjuray database access Python code from `prjuray` repo here. The code is isolated and can be imported by any external Python script.

The plan is to make this code imported by scripts in `prjuray` and `symbiflow-arch-defs`.

### CODE REVIEW

**Comment by mkurc-ant** [comment]
@tmichalak @litghost Could you please review this PR? (It looks like I don't have correct permissions to this repo to use the "ask for review" button)

**Comment by tmichalak** [comment]
@mkurc-ant LGTM
@litghost I guess you need to add this repo to the SymbiFlow group so that we can ask for reviews and possibly push to it?

**Comment by kgugala** [comment]
@mkurc-ant try now

**Comment by mkurc-ant** [comment]
@kgugala Works now, thanks.

**Review by tmichalak — APPROVED** [review]
LGTM. I guess we merge it and then open a PR to clean up prjuray?

**Comment by mkurc-ant** [comment]
@tmichalak @litghost The idea is to remove this code from `prjuray` repo and make all scripts there use `prjuray-tools` instread.

**Pull request merged**
